In [1]:
import numpy as np

5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.

(5E)* (5E)-1 = E ;
(5E)-1 = E/(5E) ;
1/5 =0.2 ;
по диагонале будет значение 0,2

In [40]:
e = np.identity(5)
x=5*e
x

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [41]:
w = np.linalg.inv(x)
w

array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])

5.2

Вычислите определитель:

In [47]:
b=np.array([[1, 2, 3], [4, 0, 6],[7, 8, 9]])
b

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [48]:
1*(0*9-8*6)-4*(2*9-8*3)+7*(2*6-0*3)

60

In [3]:
np.linalg.det(b)

59.999999999999986

5.3

Вычислите матрицу, обратную данной:

In [4]:
b=np.array([[1, 2, 3], [4, 0, 6],[7, 8, 9]])

print(b)


[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [6]:
p = np.linalg.inv(b)
p

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [9]:
np.dot(b, p)

array([[ 1.00000000e+00,  0.00000000e+00,  5.55111512e-17],
       [-4.44089210e-16,  1.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [10]:
np.dot(p, b)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-16],
       [ 1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])

 Приведите пример матрицы 4х4, ранг которой равен 1.

In [10]:
d=np.array([[1, 1, 1, 1], [1, 1, 1, 1],[1, 1, 1, 1],[1, 1, 1, 1]])

In [11]:
np.linalg.matrix_rank(d, 0.0001)

1

5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)


In [49]:
1 * 2 + 5 * 8

42

Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 


Чтобы вычислить смешанное произведение векторов, необходимо найти определитель системы, составленной из координат векторов.
Определитель:

In [44]:
o = 1*(8*3-1.5*7)-2*(5*3-1.5*0)+7*(5*7-8*0)
o

228.5

In [45]:
s=np.array([[1, 5, 0], [2, 8, 7],[7, 1.5, 3]])
s

array([[1. , 5. , 0. ],
       [2. , 8. , 7. ],
       [7. , 1.5, 3. ]])

In [46]:
np.linalg.det(s)

228.50000000000009

Поскольку определитель больше 0, то векторы образуют правую систему.