In [1]:
import numpy as np

1. Решите линейную систему: A * X= B



In [2]:
A=np.array([[1, 2, 3], [4, 0, 6],[7, 8, 9]])
A

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [3]:
B=np.array([[12], [2],[1]])
B

array([[12],
       [ 2],
       [ 1]])

In [4]:
np.linalg.solve(A, B)

array([[-9.2       ],
       [ 0.9       ],
       [ 6.46666667]])

2. Найдите псевдорешение:
x + 2y – z = 1
3x – 4y = 7
8x – 5y + 2z = 12
2x – 5z = 7
11x +4y – 7z = 15


In [5]:
A=np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
A

array([[ 1,  2, -1],
       [ 3, -4,  0],
       [ 8, -5,  2],
       [ 2,  0, -5],
       [11,  4, -7]])

In [6]:
B=np.array([[1], [7],[12], [7], [15]])
B

array([[ 1],
       [ 7],
       [12],
       [ 7],
       [15]])

In [7]:
np.linalg.lstsq(A, B)

C:\Users\vozne\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([[ 1.13919353],
        [-0.90498444],
        [-0.9009803 ]]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

3. Сколько решений имеет линейная система:

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 



In [8]:
A=np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.linalg.det(A)

432.00000000000017

In [9]:
B=np.array([[12], [2],[1]])
B

array([[12],
       [ 2],
       [ 1]])

In [10]:
np.linalg.solve(A, B)

array([[-4.05323966e+16],
       [ 8.10647933e+16],
       [-4.05323966e+16]])

4. Вычислите LU-разложение матрицы:

После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.


In [11]:
import scipy.linalg 

In [12]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P,L,U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]



5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1
8x – 5y + 2z = 12
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 



6. Найдите одно из псевдорешений вырожденной системы:

Попробуйте также отыскать и нормальное псевдорешение.
